### ISSUE TITLE
Is this still up to date?

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab/extension-cookiecutter-js#22]
I see that https://github.com/jupyterlab/extension-cookiecutter-ts has a lot more activity than this one. Is this cookiecutter still supported / updated officially? I would, but I don't really know anything about JupyterLab extensions.

**Comment by bollwyvl** [comment]
Yeah, it's still accurate! It's also theoretically part of the release
process:

https://github.com/jupyterlab/jupyterlab/blob/0c8f75d6d6cd915040881650d60d5e071371e31f/RELEASE.md

But it's not automated or anything, probably because it doesn't break!

There's really not much to know that _every_ extension would need: I guess
you could add logging the rest of the main public entry points (shell,
commandLinker, info, et al) but you're gonna need a lot more dependency
injection to, say, touch the Notebook... All without requiring or reporting
anything.

An exception would be the common kernel.js "add a codemirror mode," which
is basically a noop `activate` with the side effect of importing said mode.

I _think_ one can already start using es6 imports, which should probably be
encouraged over commonjs at this point.

My personal feeling is that we probably wouldn't want to introduce the
Babel/flow on this stack, but rather add it as a separate repo if someone
wants to own the maintenance and outreach and troubleshooting.

In that vein, some other compile-to-js-es (elm, dart, clojurescript, etc)
would be amazing.

**Comment by ian-r-rose** [comment]
It is still up-to-date in that it still works, but it does have some old cruft that should be removed. We no longer need any python components to the extension, so the python package is not necessary.

As a general rule, this cookiecutter is more stable than the typescript one because it is *unaware* of any API/typings changes that occur upstream. Because it doesn't really do anything by default, it doesn't need to be updated in light of a new published version of JupyterLab. If it actually relied on some unstable interface, then we would need to update it much more frequently.

I'm going to leave this open until we remove the outdated python.

**Comment by jrobinso** [comment]
I see its a year later and still open.  I have a jupyter notebook extension that embeds a genomic visualization into the notebook.  It includes a javascript and python component, with communication between the 2 via "comm".    https://github.com/igvteam/igv-jupyter.   I want to port it to Jupyter Lab, and I don't use typescript,  is this cookie cutter a reasonable place to start?

**Comment by jrobinso** [comment]
It does appear to be a host configuration problem.     https://www.naschenweng.info/2017/03/31/java-bypass-sslprotocolexception-handshake-alert-unrecognized_name/

**Comment by prateekrastogi** [comment]
@jrobinso  Unfortunately not, I am trying to build a pure js plugin to async fetch training data for notebooks. But, build is hanging.

**Comment by vidartf** [comment]
> is this cookie cutter a reasonable place to start?

It probably won't work perfectly out of the box, but it is likely to be helpful in setting up a healthy file structure for a new extension, and helping resolve some typical questions.

**Comment by prateekrastogi** [comment]
@vidartf I am unable to get this plugin activation msg `JupyterLab extension {{plugin}} is activated!`

I am confident about code correctness from gazing at typescript cookie cutter. It might be an upstream build issue as plugins do get registered in jupyterlab/binder i.e. install command is running properly, but build is not able to load plugin files at runtime.

**Comment by jtpio** [comment]
Closing since the cookiecutter has now been updated to use the new extension distribution system in JupyterLab 3.0 (https://github.com/jupyterlab/extension-cookiecutter-js/pull/33): https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions
